---
title: "Dashboard impact map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE , warning=FALSE}
library(flexdashboard)
library(tidyverse)
library(sf)
library(ggeasy)
library(plotly)
library(leaflet)
library(xlsx)
library(lubridate)
library(plotly)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Country map

```{r}
shape_admin0 <- read_sf("Data/adm0/wca_admbnda_adm0_ocha_18022021.shp", quiet = TRUE)
wca <- c("Benin","Burkina Faso", "Cameroon","Central African Republic","Chad","Côte d'Ivoire","Gambia","Ghana","Guinea","Guinea Bissau","Liberia","Mali","Mauritania","Niger","Nigeria","Senegal","Sierra Leone","Togo")

shape_admin0 <- shape_admin0 %>% filter(
  admin0Name %in% wca
)

g1 <- ggplot(shape_admin0) + geom_sf(aes(fill =admin0Name))+
   theme_classic() + easy_remove_x_axis() + easy_remove_y_axis() +
  easy_remove_legend()  

ggplotly(g1)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Admin1 Map

```{r}
shape_admin1 <- read_sf("Data/Admin1/wca_admbnda_adm1_ocha.shp", quiet = TRUE)

shape_admin1 <- shape_admin1 %>% filter(
  admin0Name %in% wca
)

shape_admin1 <- st_transform(shape_admin1, crs = 4326)
popupvalue <- paste0("Dahboard Admin1 " ,
                "<br>",shape_admin1$admin1Name) %>% lapply(htmltools::HTML)

pal <- colorFactor( palette =  c("#4b001d", "#1a472a", "#fdef19", "#f0ff16", "#685c68", "#6d7062", "#7b5c62", "#175617", "#ff3569", "#5a0441", "#ab0013", "#ab0068", "#e08dff", "#00ffff", "#1b4d3e", "#c3e8de", "#fa7445", "#2ad3ff"),
                    levels = c("Benin","Burkina Faso", "Cameroon","Central African Republic","Chad","Côte d'Ivoire","Gambia","Ghana","Guinea","Guinea Bissau","Liberia","Mali","Mauritania","Niger","Nigeria","Senegal","Sierra Leone","Togo"))

# pal <- colorNumeric(colors()[1:18])
g2 <- shape_admin1 %>% leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor = ~pal(shape_admin1$admin0Name),
    fillOpacity = 0.7,
    color = "white",
    popup = popupvalue,
    label = shape_admin1$admin1Name
    
  )

g2
```

### Admin2 Map

```{r}
dataset <- read.xlsx("Data/csv/xlsx.xlsx",sheetName = 1)
dataset <- dataset %>% mutate(
  Year = 2022,
  day = 1
) 


# dataset <- dataset %>% mutate(Date = make_date(Year = Year, Month = Month,day = day))

dataset <- dataset %>% mutate(Date = make_date(Year, Month,day))
dataset2 <- dataset %>% slice(-10)
g4 <- ggplot(dataset, aes(x = Date, y = anne_2022)) + geom_line( color = "blue")
g4

ggplotly(g4)


```

